### ISSUE TITLE
Environment variables are not available

### ISSUE THREAD

**Issue by frankTurtle** [nordcloud/serverless-mocha-plugin#83]
- Testing lambda function
- trying to call process.env.variableName
- getting undefined
- printed out environment variables, they're not in the list
- environment variables are accessible in regular serverless mocha tests, just not lambda functions.

**Comment by jplock** [comment]
Just ran into this myself.  Are there any workarounds?

**Comment by hazrul** [comment]
I am facing the same issue. Getting undefined for environment variables

**Comment by Thana404** [comment]
I know this issue is a bit old, but I'm too facing it, but only for a specific use case.
Basically, any environment variable defined in the "provider" can be retrieved properly using "process.env":

But any environment variable defined at a function level cannot.

```
provider
  environment:
    FOO: foo <-- I can get it in my tests with process.env
functions:
  MyFunction:
    environment:
      BAR: bar <-- I cannot
```
For now I duplicate this function's env. variables in a dedicated json file, but being able to duplicate them (and risk out-of-sync issue) would be great.
